# Book settings
title: Module 1 - Introduction to AI
author: Dr. Your Name

logo: "_static/logo.svg"
favicon: "_static/favicon.jpg"

# HTML Output Configuration
html:
  favicon: "_static/favicon.jpg"
  logo: "_static/logo.svg"
  extra_css:
    - "_static/css/extra.css"
  use_repository_button: true
  use_issues_button: true

# MathJax config (as per mkdocs-style math support)
math:
  katex: false

# Markdown parsing and extensions
parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - html_admonition
    - html_image
    - linkify
    - substitution
    - dollarmath
    - amsmath
    - attrs_inline

# Scripts and JS overrides
sphinx:
  extra_extensions:
    - sphinx_togglebutton
    - sphinx_copybutton
  config:
    html_js_files:
      - _static/javascript/tablecontentsoverride.js
      - _static/javascript/config.js
      - https://polyfill.io/v3/polyfill.min.js?features=es6
      - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    # html_extra_path:
    #   - _static/videos/my-video.mp4  # If you want to serve the video file

# Repository info
repository:
  url: https://github.com/MSc-in-AI-Programme/Module1
  path_to_book: notebooks
  branch: main

# Notebooks execution settings
execute:
  execute_notebooks: force

# Launch buttons (Codespaces enabled, thebe optional)
launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: ""
  binderhub_url: ""
  thebe: false
  jupyterhub_url: ""
  codespaces: true

# Citation support
bibtex_bibfiles:
  - references.bib

# LaTeX PDF generation
latex:
  latex_documents:
    targetname: book.tex
