# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Module 1- Introduciton to AI
author: Dr. Your Name

theme:
  name: "material"
  custom_dir: "overrides"        # Only once
  features:
    - navigation.tabs
    - navigation.sections
  font:
    text: "Inter"

html:
  logo: "_static/logo.svg"
  favicon: "_static/favicon.jpg"
  extra_css:
    - "_static/extra.css"
    - "static/css/extra.css"     # If this exists in your overrides directory


# repository:
#   url: https://github.com/YourOrg/YourRepo
#   path_to_book: notebooks
#   branch: main



# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/MSc-in-AI-Programme/Module1 #https://github.com/executablebooks/jupyter-book  # Online location of your book
  # path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main # master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: ""
  binderhub_url: ""
  thebe: false
  jupyterhub_url: ""
  codespaces: true

