name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - ipywidgets
  - pip
  - pip:
      - jupyter-book
